server:
  port: 8091
  error:
    include-message: always

# datasource
spring:
  application:
    name: sala
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./ms-sala/data/bd-sala
    username: sa
    password:
  # jpa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  # h2
  h2:
    console:
      enabled: true
      path: /h2-console

eureka:
  instance:
    hostname: localhost
    health-check-url-path: /actuator/health
    status-page-url-path: /actuator/health

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
